package io.github.isharafe.authorization.domain;

public enum AuthorizationReason {
  PUBLIC_RESOURCE,
  AUTHENTICATION_REQUIRED,
  AUTHENTICATED,
  EXPLICIT_DENY,
  NO_MATCHING_RULE,
  MATCHING_PERMISSION,
  MISSING_PERMISSION,
  PROVIDER_UNAVAILABLE,
  CONFLICTING_RULES
}
