UPDATE AUTH_PERMISSION
SET RESOURCE_PATTERN = HTTP_METHOD || ':' || RESOURCE_PATTERN
WHERE RESOURCE_TYPE = 'URL';

UPDATE AUTH_RESOURCE_RULE
SET RESOURCE_PATTERN = HTTP_METHOD || ':' || RESOURCE_PATTERN
WHERE RESOURCE_TYPE = 'URL';

ALTER TABLE AUTH_PERMISSION DROP COLUMN HTTP_METHOD;
ALTER TABLE AUTH_RESOURCE_RULE DROP COLUMN HTTP_METHOD;
