ALTER TABLE AUTH_AUDIT_EVENT ADD COLUMN EVENT_TARGET VARCHAR(1000);
ALTER TABLE AUTH_AUDIT_EVENT ADD COLUMN AUDIT_ACTION VARCHAR(100);
ALTER TABLE AUTH_AUDIT_EVENT ADD COLUMN CORRELATION_ID VARCHAR(255);
ALTER TABLE AUTH_AUDIT_EVENT ADD COLUMN DETAILS_JSON VARCHAR(4000);
