ALTER TABLE AUTH_AUDIT_EVENT ADD COLUMN EVENT_KIND VARCHAR(30);

UPDATE AUTH_AUDIT_EVENT
SET EVENT_KIND =
  CASE
    WHEN DECISION IS NOT NULL
      OR EVENT_TYPE LIKE 'AUTHORIZATION!_%' ESCAPE '!'
    THEN 'DECISION'
    ELSE 'CHANGE'
  END;

ALTER TABLE AUTH_AUDIT_EVENT ALTER COLUMN EVENT_KIND SET NOT NULL;

CREATE INDEX IX_AUTH_AUDIT_EVENT_KIND ON AUTH_AUDIT_EVENT(EVENT_KIND);
